spring:
  data:
    mongodb:
      authentication-database: admin
      username: community_admin
      password:  D5NYJq8M2W
      database: cc_discount_code
      port: 27017
      host: staging-api.thecommunity-connect.com  #44.238.64.77
