spring:
  data:
    mongodb:
      authentication-database: admin
      #username: community_admin
      #password:  D5NYJq8M2W
      database: cc_discountcode
      #port: 27017
      #host: 103.205.140.61


trs:
  defaults:
    pagingLimit: 10
  env: DEV

jwt:
  secret: dev_test_secret

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

server:
  port: 3012


rmq:
  email:
    queueName: com.trs.cc.notification.email
    exchangeName: com.trs.community.connect
    routingKey: cc.notification.email
  sms:
    queueName: com.trs.cc.notification.sms
    exchangeName: com.trs.community.connect
    routingKey: cc.notification.sms
  notification:
    queueName: com.trs.cc.notification.push
    exchangeName: com.trs.community.connect
    routingKey: cc.notification.notification
