spring:
  data:
    mongodb:
      authentication-database: admin
      username: community_admin
      password:  D5NYJq8M2W
      database: cc_discount_code
      port: 27017
      host: 103.205.140.61
