spring:
  data:
    mongodb:
      uri: mongodb+srv://community_admin:D5NYJq8M2W@main-cluster.hk9ov.mongodb.net/cc_discount_code?retryWrites=true&w=majority
      database: cc_discount_code
#      authentication-database: admin
#      username: community_admin
#      password:  D5NYJq8M2W
#      port: 27017
#      host: staging-api.thecommunity-connect.com  #44.238.64.77
  messages:
    basename: messages
    always-use-message-format: false
    encoding: UTF-8
    fallback-to-system-locale: true
    use-code-as-default-message: false

trs:
  defaults:
    pagingLimit: 10
  env: DEV

jwt:
  secret: dev_test_secret

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

server:
  port: 3012


rmq:
  email:
    queueName: com.trs.cc.notification.email
    exchangeName: com.trs.community.connect
    routingKey: cc.notification.email
  sms:
    queueName: com.trs.cc.notification.sms
    exchangeName: com.trs.community.connect
    routingKey: cc.notification.sms
  notification:
    queueName: com.trs.cc.notification.push
    exchangeName: com.trs.community.connect
    routingKey: cc.notification.notification
